services:
  - type: web
    name: smart-meeting-agent
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORTIA_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: BROWSERBASE_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: true